version: '3.4'
services:
  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    tty: true
    env_file:
      - passbolt.env
    volumes:
      - ./data/gpg_volume:/etc/passbolt/gpg
      - ./data/images_volume:/usr/share/php/passbolt/webroot/img/public
    command: ["/usr/bin/wait-for.sh", "-t", "0", "192.168.0.65:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 8001:80
      - 443:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433

volumes:
  gpg_volume:
  images_volume:
